server:
  port: 11520

spring:
  datasource:
    url: jdbc:sqlite:${user.home}/.eddie-ai/eddie-ai.db
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
